export { default as category_3d } from "./category-3d.png";
export { default as category_design } from "./category-design.png";
export { default as category_font } from "./category-font.png";
export { default as category_illustration } from "./category-illustration.png";
export { default as category_photography } from "./category-photography.png";
export { default as category_uiux } from "./category-uiux.png";
export { default as category_videography } from "./category-videography.png";
export { default as category_web } from "./category-web.png";
export { default as category_unggulan } from "./category-unggulan.png";